# Permalinks
permalink:           pretty

# Setup
title:               Aldo Kelvianto
tagline:             Android Developer from Jakarta.
url:                 http://aldokelvianto.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aldo Kelvianto
  url:               https://twitter.com/aldokelvianto
  email:             jami0821@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/aldokelvianto/aldokelvianto.github.io
google_analytics:    UA-3363703-15
twitter:             aldokelvianto
github:              aldokelvianto
dribbble:            aldokelvianto

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
